name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Setup User & LFS
          git config --global user.email "anggariantosudrajat@gmail.com"
          git config --global user.name "Angga Rianto Sudrajat"
          git lfs install
          
          # 2. Add Remote Hugging Face
          git remote add space https://anggars:$HF_TOKEN@huggingface.co/spaces/anggars/sentimind-api
          
          # 3. TRICK: Download Model Asli dari HF Space
          # Kita ambil file model yang udah ada di HF dan masukin ke folder commit ini
          # Jadi pas di-push, modelnya tetep ada (gak kehapus)
          
          echo "Downloading models from Hugging Face..."
          curl -L -H "Authorization: Bearer $HF_TOKEN" https://huggingface.co/spaces/anggars/sentimind-api/resolve/main/api/data/model_mbti.pkl -o api/data/model_mbti.pkl
          curl -L -H "Authorization: Bearer $HF_TOKEN" https://huggingface.co/spaces/anggars/sentimind-api/resolve/main/api/data/model_emotion.pkl -o api/data/model_emotion.pkl
          
          # 4. Pastikan file model ke-track sebagai LFS
          git lfs track "api/data/*.pkl"
          git add .gitattributes
          
          # 5. Masukkan model yang barusan didownload ke dalam antrian commit
          git add api/data/*.pkl
          
          # 6. "Amend" (Selipkan) model ini ke commit terakhir dari GitHub
          git commit --amend --no-edit
          
          # 7. Push Force (Aman karena modelnya udah kita bawa)
          git push --force space main